### ISSUE TITLE
/Applications

### ISSUE THREAD

**Issue by jun6lee** [cesalazar/alfred-open-with#1]
I do have HomeBrew, so this may just be my ignorance, but if I want to Open with "Preview", do I need to make a separate symlink? It's only showing a handful of Application options on install.

**Comment by cesalazar** [comment]
Hey @jun6lee, sorry for the late reply but somehow I never got a notification about this issue.

To be honest, I have no clue: I stopped using OSX/MacOS years ago, and I don't even remember the annoyance this workflow solved for me. I'd be surprised if this still works in the current version of Alfred and MacOS.
